# Generated by Django 4.0.4 on 2022-04-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
    ]
