# Generated by Django 4.0.4 on 2022-04-16 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_property_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
