# Generated by Django 4.0.4 on 2022-04-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
